name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/soundboardbot:latest

  update_k8s:
    runs-on: ubuntu-latest
    needs: push_docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup KubeConfig
        run:  |
          mkdir ~/.kube
          touch ~/.kube/config
          echo "$KUBECONFIG_DATA" > ~/.kube/config
        env:
          KUBECONFIG_DATA : ${{secrets.KUBECONFIG_DATA}}
      - name: Setup kubectl
        uses: azure/setup-kubectl@v2.0
      - name: Kubectl Version
        run: kubectl version
      - name: Configure k8s Deployment
        run: kubectl apply -f ./k8s/deployment.yaml
      - name: Update k8s Deployment
        run: kubectl rollout restart deployment/soundboardbot
